# ExternalSecret: syncs DB credentials from GCP Secret Manager into a K8s Secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudsql-credentials
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudsql-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: food-ordering-db-username
    - secretKey: password
      remoteRef:
        key: food-ordering-db-password
