{{- range $name, $config := .Values.services }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}-sa
  namespace: {{ $.Values.namespace }}
  annotations:
    # Workload Identity: binds this K8s SA to the GCP SA that has Cloud SQL access
    iam.gke.io/gcp-service-account: {{ $.Values.cloudSqlProxySA }}
  labels:
    app: {{ $name }}
    {{- include "food-ordering.labels" $ | nindent 4 }}
---
{{- end }}
